### ISSUE TITLE
Uncaught Error: Call to undefined function Laravel\Installer\Console\mb_rtrim()

### ISSUE THREAD

**Issue by didix16** [laravel/installer#372]
### Installer Version

5.11.0

### Description

I'm on Windows 11 machine using 8.2 PHP version.
While trying to install Laravel using the installer, after choosing the testing framework I've got an exception.

```bash
PHP Fatal error:  Uncaught Error: Call to undefined function Laravel\Installer\Console\mb_rtrim() in C:\Users\User\AppData\Roaming\Composer\vendor\laravel\installer\src\NewCommand.php:162
Stack trace:
#0 C:\Users\User\AppData\Roaming\Composer\vendor\symfony\console\Command\Command.php(279): Laravel\Installer\Console\NewCommand->execute()
#1 C:\Users\User\AppData\Roaming\Composer\vendor\symfony\console\Application.php(1029): Symfony\Component\Console\Command\Command->run()
#2 C:\Users\User\AppData\Roaming\Composer\vendor\symfony\console\Application.php(316): Symfony\Component\Console\Application->doRunCommand()
#3 C:\Users\User\AppData\Roaming\Composer\vendor\symfony\console\Application.php(167): Symfony\Component\Console\Application->doRun()
#4 C:\Users\User\AppData\Roaming\Composer\vendor\laravel\installer\bin\laravel(13): Symfony\Component\Console\Application->run()
#5 C:\Users\User\AppData\Roaming\Composer\vendor\bin\laravel(119): include('...')
#6 {main}
  thrown in C:\Users\User\AppData\Roaming\Composer\vendor\laravel\installer\src\NewCommand.php on line 162
```

### Steps To Reproduce

```$ laravel new test-app```
```
 Would you like to install a starter kit? [No starter kit]:
  [none     ] No starter kit
  [breeze   ] Laravel Breeze
  [jetstream] Laravel Jetstream
 > breeze


 Which Breeze stack would you like to install? [Blade with Alpine]:
  [blade              ] Blade with Alpine
  [livewire           ] Livewire (Volt Class API) with Alpine
  [livewire-functional] Livewire (Volt Functional API) with Alpine
  [react              ] React with Inertia
  [vue                ] Vue with Inertia
  [api                ] API only
 > react


 Would you like any optional features? [None]:
  [none      ] None
  [dark      ] Dark mode
  [ssr       ] Inertia SSR
  [typescript] TypeScript
  [eslint    ] ESLint with Prettier
 > typescript,dark


 Which testing framework do you prefer? [Pest]:
  [0] Pest
  [1] PHPUnit
 >

PHP Fatal error:  Uncaught Error: Call to undefined function Laravel\Installer\Console\mb_rtrim() in C:\Users\User\AppData\Roaming\Composer\vendor\laravel\installer\src\NewCommand.php:162
...
```

**Comment by crynobone** [comment]
@didix16 Thanks for the report. It seems like your installation missing `mbstring` extension or PHP 8.4

To solve this without waiting for a new `installer` release you should be able to run the following:

```shell
composer global require symfony/polyfill-mbstring
```

**Comment by didix16** [comment]
Thanks for you fast response @crynobone !

**Comment by didix16** [comment]
@crynobone I've had already activated the mbstring extension. I had it since I was installed the PHP 8.2 version. I just installed the symfony/polyfill-mbstring package globally and worked like a charm. Thanks!
